<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Tue, 05 Jun 2018 19:26:15 +0800
 */

$conf['title'] = 'Keeper';
$conf['start'] = 'index';
$conf['lang'] = 'zh';
$conf['template'] = 'bootstrap3';
$conf['tagline'] = 'GoGoGo';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['authmysql']['TablesToLock'] = array();

// end auto-generated content
